env: 'local'
config_path: './config/db_config.yaml'
url : "http://recommendation-engine.endpoints.newsuk-datatech-prod.cloud.goog/products/{product}/users/{userid}/recommendations?key=AIzaSyCwiYqn74kzpN6iCvu2BtDMMRERPsvIwyo"
